#!/usr/bin/env python3
"""A package whose enforced behaviour changed must carry a new version.

Twice now a rule contract changed under an unchanged version label, and both times
core caught it rather than this repo. The first time, eight packages changed what they
enforce and stayed 0.1.0 while core was told to re-pin. The second, 0.2.0 was shipped
and then fifteen more files landed across the same two packages under that same label
within a day — including 94 lines of detector logic. A downstream lock records a
VERSION; if the version does not move, the lock cannot express the difference, which is
the whole failure #1818 is about.

Neither promise nor review caught it. This does, by construction: the digest below
covers exactly the files that decide what a package enforces — its manifest, its
convention nodes, and its detector sources. Change any of them and the digest moves; if
the version did not move too, this fails.

Fixtures and tests are deliberately EXCLUDED. A better fixture does not change what a
consumer must satisfy, and coupling them here would make the guard cry wolf on every
test improvement until people learned to run --update without reading it.

    python3 tools/check_version_bumps.py            # fail if behaviour moved and version did not
    python3 tools/check_version_bumps.py --update   # re-record after an intentional bump
"""
from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

import yaml

HUB = pathlib.Path(__file__).resolve().parent.parent
LEDGER = HUB / "registry" / "version-digests.yaml"

# What decides enforced behaviour: the manifest, the obligations, the detector code.
BEHAVIOUR_GLOBS = (
    "atdd.extension.yaml",
    "atdd.workspace.yaml",
    "conventions/*.yaml",
    "relationships.yaml",
    "implementations/*/atdd.implementation.yaml",
    "implementations/*/**/*.py",
    "implementations/*/**/*.mjs",
    "implementations/*/**/*.js",
)


def behaviour_files(pkg: pathlib.Path) -> list[pathlib.Path]:
    out: set[pathlib.Path] = set()
    for pattern in BEHAVIOUR_GLOBS:
        for f in pkg.glob(pattern):
            if not f.is_file():
                continue
            parts = f.relative_to(pkg).parts
            if "fixtures" in parts or "tests" in parts or "conformance" in parts:
                continue
            if f.name.startswith("test_") or ".test." in f.name or ".spec." in f.name:
                continue
            out.add(f)
    return sorted(out)


def digest(pkg: pathlib.Path) -> str:
    h = hashlib.sha256()
    for f in behaviour_files(pkg):
        h.update(str(f.relative_to(pkg)).encode())
        h.update(b"\0")
        h.update(f.read_bytes())
        h.update(b"\0")
    return h.hexdigest()


def version_of(pkg: pathlib.Path) -> str | None:
    for name in ("atdd.extension.yaml", "atdd.workspace.yaml"):
        m = pkg / name
        if m.is_file():
            doc = yaml.safe_load(m.read_text()) or {}
            v = doc.get("version")
            return str(v) if v is not None else None
    return None


def survey() -> dict[str, dict[str, str]]:
    out: dict[str, dict[str, str]] = {}
    for pkg in sorted(HUB.glob("official/*")):
        if not pkg.is_dir():
            continue
        v = version_of(pkg)
        if v is None:
            continue
        out[pkg.name] = {"version": v, "digest": digest(pkg)}
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--update", action="store_true",
                    help="re-record the ledger after an intentional bump")
    args = ap.parse_args()

    current = survey()

    if args.update:
        LEDGER.parent.mkdir(parents=True, exist_ok=True)
        LEDGER.write_text(
            "# GENERATED by tools/check_version_bumps.py --update — DO NOT EDIT BY HAND.\n"
            "#\n"
            "# One entry per package: the version it last published, and a digest over the\n"
            "# files that decide what it enforces. If the digest moves and the version does\n"
            "# not, the check fails — a downstream lock records a version, so a version that\n"
            "# does not move cannot express the change.\n"
            + yaml.safe_dump(current, sort_keys=True)
        )
        print(f"recorded {len(current)} package(s) in {LEDGER.relative_to(HUB)}")
        return 0

    if not LEDGER.is_file():
        print(f"{LEDGER.relative_to(HUB)} is missing; run --update to record a baseline",
              file=sys.stderr)
        return 1

    previous = yaml.safe_load(LEDGER.read_text()) or {}
    stale: list[str] = []
    for name, now in current.items():
        was = previous.get(name)
        if was is None:
            continue                                   # new package: nothing to compare
        if now["digest"] != was["digest"] and now["version"] == was["version"]:
            stale.append(f"{name}: still {now['version']}, but what it enforces changed")

    if stale:
        print(f"{len(stale)} package(s) changed behaviour without a version bump:\n",
              file=sys.stderr)
        for line in stale:
            print(f"  - {line}", file=sys.stderr)
        print("\nA downstream lock records a VERSION. Bump each package, then re-record:\n"
              "  python3 tools/check_version_bumps.py --update", file=sys.stderr)
        return 1

    print(f"{len(current)} package(s): every behaviour change carries a version bump")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
